name: "Test FOSSology scan"
description: "Run license and copyright scans"
branding:
  icon: "search"
  color: "orange"
inputs:
  scan-mode:
    description: "Whether to do diff scans, repo scan or differential scan"
    required: false
    default: ""
  scanners:
    description: "Which scanners to invoke"
    required: true
    default: "nomos ojo copyright keyword"
  github_api_url:
    description: "Base URL of Github API"
    required: false
    default: ${{ github.api_url }}
  github_repository:
    description: "Repository name"
    required: false
    default: ${{ github.repository }}
  github_token:
    description: "Github Token"
    required: false
    default: ${{ github.token }}
  github_pull_request:
    description: "Github PR"
    required: false
    default: ${{ github.event.number }}
  github_repo_url:
    description: "Github Repo URL"
    required: false
    default: ${{ github.repositoryUrl }}
  github_repo_owner:
    description: "Github Repo Owner"
    required: false
    default: ${{ github.repository_owner }}
  base_ref:
    description: "Target branch"
    required: false
    default: ${{ github.base_ref }}
  head_ref:
    description: "Source branch"
    required: false
    default: ${{ github.head_ref }}

runs:
  using: "composite"
  steps:
    - name: Run FOSSology scan in Docker
      shell: bash
      run: |
        docker run --rm \
          -e SCAN_MODE="${{ inputs.scan-mode }}" \
          -e SCANNERS="${{ inputs.scanners }}" \
          -e API_URL="${{ inputs.api_url }}" \
          -e REPOSITORY="${{ inputs.repository }}" \
          -e GITHUB_TOKEN="${{ inputs.github_token }}" \
          -e GITHUB_PULL_REQUEST="${{ inputs.github_pull_request }}" \
          -e BASE_REF="${{ inputs.base_ref }}" \
          -e HEAD_REF="${{ inputs.head_ref }}" \
          rjknightmare/fo-ci-test:latest \
          /bin/fossologyscanner ${{ inputs.scan-mode }} $(echo ${{ inputs.scanners }} | tr ' ' '\n')

# runs:
#   using: "docker"
#   image: "docker://rjknightmare/fo-ci-test:latest"
#   shell: bash
#     run: |
#       /bin/fossologyscanner ${{ inputs.scan-mode }} ${scanners[@]}
#   env:
#     GITHUB_API: ${{ inputs.api_url }}
#     GITHUB_REPOSITORY: ${{ inputs.repository }}
#     GITHUB_TOKEN: ${{ inputs.github_token }}
#     GITHUB_PULL_REQUEST: ${{ inputs.github_pull_request }}
#     BASE_REF: ${{ inputs.base_ref }}
#     HEAD_REF: ${{ inputs.head_ref }}
#     GITHUB_REPO_URL: ${{ inputs.github_repo_url }}
#     GITHUB_REPO_OWNER: ${{ inputs.github_repo_owner }}

# // TODO Figure out how to pass lists as args
# // TODO Figure out what we can do for cross platform compatibility. Now user needs to add qemu.
# // TODO Figure out what other things we can do or is there a better way to do this?
# // TODO How to pass diff scans input to the script. Probably need to change the script itself to handle this or try other solutions as well.
