name: Run test fo-ci-scan
on:
  - push

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    name: Run fossology CI scanner
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Run fossology scanners in docker container
        uses: ./
        with:
          scan-mode: "differential"
          scanners: "nomos ojo copyright keyword"
          from_tag: "v001"
          to_tag: "v005"
          # allowlist_file_path: "src/allowlist.test.json"
          # keyword_conf_file_path: "/usr/var/local/share/keyword.test.conf"
